# Generated by Django 6.0.6 on 2026-07-02 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nombre_completo',
            field=models.CharField(default=12345, max_length=200),
            preserve_default=False,
        ),
    ]
