# Generated by Django 6.0.6 on 2026-07-02 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usuario_nombre_completo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nombre_completo',
        ),
    ]
