# Generated by Django 6.0.6 on 2026-07-02 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_usuario_nombre_completo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='clase',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Clase'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='curso',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Curso'),
        ),
    ]
