# Generated by Django 6.0.6 on 2026-07-02 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_usuario_clase_usuario_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='clase',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='curso',
        ),
    ]
